version: '3.7'
services:
  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    container_name: local_user_tag_mongo
